### PR TITLE
Add converting of schemas using swagger/convert API endpoint

### PR DESCRIPTION
**Pull request by jhowlett-scottlogic**
PR for https://github.com/ScottLogic/openapi-forge/issues/9

Using API endpoint `https://converter.swagger.io/api/convert` to convert to OpenAPI v3.

I have tested v2 of the petstore in both yaml & json format. I have not found a OpenAPI v1 schema to test but the documentation for the endpoint states it can handle both v1 & v2 schemas.

There is no way to know what version of OpenAPI the schema currently is so all schemas are converted.

### CODE REVIEW

**Review by ColinEberhardt — CHANGES_REQUESTED** [review]
This works, but it does have a few issues.

 - I imagine people will want to run this within a CI environment. In this case, the accessible domains may be restricted (I'd hope so!)
 - Probably more significant, I'm not keen on the idea of passing someone's data to a third party service, without giving them the option or notice.

Can the swagger converter be used offline perhaps?

**Comment by jhowlett-scottlogic** [comment]
I didnt think about the problems with using an External API. 

There are NPM packages that can convert v2 -> v3.

This [package](https://www.npmjs.com/package/swagger2openapi) is the most used is this and only has 11 dependencies. It's [GitHub](https://github.com/Mermade/oas-kit/tree/main/packages/swagger2openapi) looks active and is in a sustainable state.

**Comment by ColinEberhardt** [comment]
> This [package](https://www.npmjs.com/package/swagger2openapi)'s only function is to convert v2 -> v3 (therefore no excess functionality) and only has 11 dependencies. It's [GitHub](https://github.com/Mermade/oas-kit/tree/main/packages/swagger2openapi) looks active and is in a sustainable state.

I'd be happy with that option 👍

**Comment by jhowlett-scottlogic** [comment]
Moved over to using swagger2openapi modules. It has added 39 packages in total (54 -> 93 dependencies in the project now).

Only converts when it finds a valid v2 schema (`swagger: "2.0"` is a required field in v2).

**Review by ColinEberhardt — APPROVED** [review]

**Comment by ColinEberhardt** [comment]
Fantastic, thanks for the updates @jhowlett-scottlogic

**Pull request merged**
